# Site settings
title: Bitcoin Fees
email: bitcoinfees@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Real-time bitcoin transaction fee estimation
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://bitcoinfees.github.io" # the base hostname & protocol for your site
github_username:  bitcoinfees

# Build settings
markdown: kramdown
